### ISSUE TITLE
"Invalid input."

### ISSUE THREAD

**Issue by vgoklani** [gavinr/arcgis-json-to-geojson#23]
Hey there - I downloaded some geo data and was told it was ArcGIS JSON:

    {'displayFieldName': 'NAME',
     'fieldAliases': {},
     'geometryType': 'esriGeometryPolygon',
     'spatialReference': {'wkid': 102100, 'latestWkid': 3857},
     'fields': [],
     'features': [{'attributes': {'OBJECTID': 2050,
        'PRECINCTID': '01029B',
        'NAME': 'COLUMBUS 29-B',
        'COUNTY': None,
        'ESS_PRECINCT_NO': None,
        'ESS_PRECINCT': None,
        'CITY_OR_VILLAGE': None,
        'SCHOOL_DISTRICT': None,
        'TOWNSHIP': None,
        'HOUSE_DISTRICT': None,
        'SENATE_DISTRICT': None,
        'CONGRESS_DISTRICT': None,
        'POLICE_DISTRICT': None,
        'ROAD_DISTRICT': None,
        'FIRE_DISTRICT': None,
        'PARK_DISTRICT': None,
        'COURT_APPEALS_NAME': None,
        'BOARD_OF_ED_NAME': None,
        'LIBRARY': None,
        'EDUCATIONAL_SERVICE_CENTERS': None,
        'CAREER_CENTERS': None,
        'WINNINGPARTY': None,
        'TOTALBALLOTS': None,
        'SHAPE_Length': 26636.15475759097,
        'SHAPE_Area': 30443700.474467456,
        'POLLINGID': None,
        'POLLINGLOCATION': None,
        'LID': 'N/A',
        'Symbol': 'A'},
       'geometry': {'rings': [[[-9235687, 4854329],
          [-9235918, 4851467],
          [-9239010, 4854564],
          [-9235687, 4854329]]]}},
    ]}

but I get "invalid input" when i enter this in the web console.

Is there something specific i can change to convert it to geojson? Thanks!

**Comment by gavinr** [comment]
hi @vgoklani - that's invalid JSON - please go to https://jsonlint.com to help figure out where the issues are. I also updated the error message so it's more helpful in this situation in the future. (0a4c6d1) - thanks for asking about this!
